kfsyConstant = {}

local var_0_0 = 124
local var_0_1 = 64
local var_0_2 = 100
local var_0_3 = 330
local var_0_4 = 620
local var_0_5 = 600

kfsyConstant.king = ccp(190, 590)
kfsyConstant.yanjiu = {}
kfsyConstant.yanjiu[1] = {}
kfsyConstant.yanjiu[1].x = 80
kfsyConstant.yanjiu[1].y = 65
kfsyConstant.yanjiu[2] = {}
kfsyConstant.yanjiu[2].x = -70
kfsyConstant.yanjiu[2].y = -10
kfsyConstant.people = {}
kfsyConstant.people[1] = {}
kfsyConstant.people[1].side = 1
kfsyConstant.people[1].pos = ccp(var_0_2, var_0_3)
kfsyConstant.people[2] = {}
kfsyConstant.people[2].side = 2
kfsyConstant.people[2].pos = ccp(var_0_4, var_0_5)
kfsyConstant.people[3] = {}
kfsyConstant.people[3].side = 1
kfsyConstant.people[3].pos = ccp(var_0_2 + var_0_0, var_0_3 - var_0_1)
kfsyConstant.people[4] = {}
kfsyConstant.people[4].side = 2
kfsyConstant.people[4].pos = ccp(var_0_4 + var_0_0, var_0_5 - var_0_1)
kfsyConstant.people[5] = {}
kfsyConstant.people[5].side = 1
kfsyConstant.people[5].pos = ccp(var_0_2 + var_0_0 * 2, var_0_3 - var_0_1 * 2)
kfsyConstant.people[6] = {}
kfsyConstant.people[6].side = 2
kfsyConstant.people[6].pos = ccp(var_0_4 + var_0_0 * 2, var_0_5 - var_0_1 * 2)
kfsyConstant.people[7] = {}
kfsyConstant.people[7].side = 1
kfsyConstant.people[7].pos = ccp(var_0_2 + var_0_0 * 3, var_0_3 - var_0_1 * 3)
kfsyConstant.people[8] = {}
kfsyConstant.people[8].side = 2
kfsyConstant.people[8].pos = ccp(var_0_4 + var_0_0 * 3, var_0_5 - var_0_1 * 3)
kfsyConstant.people[9] = {}
kfsyConstant.people[9].side = 1
kfsyConstant.people[9].pos = ccp(var_0_2 + var_0_0 * 4, var_0_3 - var_0_1 * 4)
kfsyConstant.people[10] = {}
kfsyConstant.people[10].side = 2
kfsyConstant.people[10].pos = ccp(var_0_4 + var_0_0 * 4, var_0_5 - var_0_1 * 4)
kfsyConstant.nation = {}
kfsyConstant.nation.length = 80
kfsyConstant.nation[1] = {}
kfsyConstant.nation[1].x = 0 * kfsyConstant.nation.length
kfsyConstant.nation[1].y = 1 * kfsyConstant.nation.length
kfsyConstant.nation[2] = {}
kfsyConstant.nation[2].x = 0.58 * kfsyConstant.nation.length
kfsyConstant.nation[2].y = 0.8 * kfsyConstant.nation.length
kfsyConstant.nation[3] = {}
kfsyConstant.nation[3].x = 0.95 * kfsyConstant.nation.length
kfsyConstant.nation[3].y = 0.3 * kfsyConstant.nation.length
kfsyConstant.nation[4] = {}
kfsyConstant.nation[4].x = 0.95 * kfsyConstant.nation.length
kfsyConstant.nation[4].y = -0.3 * kfsyConstant.nation.length
kfsyConstant.nation[5] = {}
kfsyConstant.nation[5].x = 0.58 * kfsyConstant.nation.length
kfsyConstant.nation[5].y = -0.8 * kfsyConstant.nation.length
kfsyConstant.nation[6] = {}
kfsyConstant.nation[6].x = 0 * kfsyConstant.nation.length
kfsyConstant.nation[6].y = -1 * kfsyConstant.nation.length
kfsyConstant.nation[7] = {}
kfsyConstant.nation[7].x = -0.58 * kfsyConstant.nation.length
kfsyConstant.nation[7].y = -0.8 * kfsyConstant.nation.length
kfsyConstant.nation[8] = {}
kfsyConstant.nation[8].x = -0.95 * kfsyConstant.nation.length
kfsyConstant.nation[8].y = -0.3 * kfsyConstant.nation.length
kfsyConstant.nation[9] = {}
kfsyConstant.nation[9].x = -0.95 * kfsyConstant.nation.length
kfsyConstant.nation[9].y = 0.3 * kfsyConstant.nation.length
kfsyConstant.nation[10] = {}
kfsyConstant.nation[10].x = -0.58 * kfsyConstant.nation.length
kfsyConstant.nation[10].y = 0.8 * kfsyConstant.nation.length
