celebration.constant = {}
celebration.constant[1] = {}
celebration.constant[2] = {}
celebration.constant[3] = {}
celebration.constant[4] = {}
celebration.constant[5] = {}
celebration.constant[6] = {}
celebration.constant[7] = {}
celebration.constant[1].pos = ccp(-160, 180)
celebration.constant[2].pos = ccp(-160, 180)
celebration.constant[3].pos = ccp(-200, -180)
celebration.constant[4].pos = ccp(280, 40)
celebration.constant[5].pos = ccp(100, -300)
celebration.constant[6].pos = ccp(90, 250)
celebration.constant[7].pos = ccp(-230, -70)
celebration.constant[1].delay1 = 4
celebration.constant[2].delay1 = 4
celebration.constant[3].delay1 = 2
celebration.constant[4].delay1 = 2
celebration.constant[5].delay1 = 4
celebration.constant[6].delay1 = 2
celebration.constant[7].delay1 = 2
celebration.constant[1].delay2 = 4
celebration.constant[2].delay2 = 4
celebration.constant[3].delay2 = 6
celebration.constant[4].delay2 = 2
celebration.constant[5].delay2 = 2
celebration.constant[6].delay2 = 2
celebration.constant[7].delay2 = 6
celebration.constant[1].visible1 = true
celebration.constant[2].visible1 = false
celebration.constant[3].visible1 = true
celebration.constant[4].visible1 = false
celebration.constant[5].visible1 = false
celebration.constant[6].visible1 = false
celebration.constant[7].visible1 = true
celebration.constant[1].visible2 = false
celebration.constant[2].visible2 = true
celebration.constant[3].visible2 = false
celebration.constant[4].visible2 = true
celebration.constant[5].visible2 = true
celebration.constant[6].visible2 = true
celebration.constant[7].visible2 = false
