threeColorBag.constant = {}
threeColorBag.constant.state = {}
threeColorBag.constant.res = "res/ui/instance/instanceMap.plist"
threeColorBag.constant.baoshikuang = {}
threeColorBag.constant.baoshikuang.x = -1
threeColorBag.constant.baoshikuang.y = 6
threeColorBag.constant.centerbag = {}
threeColorBag.constant.centerbag.x = -5
threeColorBag.constant.centerbag.y = 0
threeColorBag.constant.kuang = {}
threeColorBag.constant.kuang[1] = ccp(-106, 104)
threeColorBag.constant.kuang[2] = ccp(106, -88)
threeColorBag.constant.kuang[3] = ccp(106, 104)
threeColorBag.constant.word = {}
threeColorBag.constant.word[1] = language.get(320301)
threeColorBag.constant.jumpHeight = 50
threeColorBag.constant.jumpTime = 0.35
threeColorBag.constant.jumpNum = 1
threeColorBag.constant.gem = {}
threeColorBag.constant.gem[1] = ccp(-120, -60)
threeColorBag.constant.gem[2] = ccp(70, -80)
threeColorBag.constant.gem[3] = ccp(-60, -70)
threeColorBag.constant.gem[4] = ccp(30, -70)
threeColorBag.constant.gem[5] = ccp(0, -60)
threeColorBag.constant.gem[6] = ccp(-40, -40)
threeColorBag.constant.gem[7] = ccp(20, -70)
threeColorBag.constant.gem[8] = ccp(100, -30)
threeColorBag.constant.gem[9] = ccp(-50, -80)
threeColorBag.constant.gem[10] = ccp(70, -60)
threeColorBag.constant.gem[11] = ccp(60, -70)
threeColorBag.constant.gem[12] = ccp(-60, -70)
threeColorBag.constant.gem[13] = ccp(-40, -30)
threeColorBag.constant.gem[14] = ccp(50, -80)
threeColorBag.constant.gem[15] = ccp(40, -20)
threeColorBag.constant.gem[16] = ccp(-30, -60)
threeColorBag.constant.gem[17] = ccp(20, -70)
threeColorBag.constant.gem[18] = ccp(90, -50)
threeColorBag.constant.bag = {}
threeColorBag.constant.bag[1] = ccp(90, -70)
threeColorBag.constant.bag[2] = ccp(70, -20)
threeColorBag.constant.bag[3] = ccp(-10, -50)
threeColorBag.constant.bag[4] = ccp(-60, -30)
threeColorBag.constant.bag[5] = ccp(-90, -40)
