loginConstant = {}
loginConstant.NAME_TEXTFIELD_TAG = 1001
loginConstant.PASSWORD_TEXTFIELD_TAG = 1002
loginConstant.REGISTER_MENUITEM_TAG = 2001
loginConstant.LOGIN_MENUITEM_TAG = 2002
loginTag = {}
loginTag.subScene = 101
loginTag.subUi = 100
loginTag.serverList = 102
loginTag.startGame = 103
loginTag.astLogin = 104
loginTag.firstStart = 105
loginTag.astRegister = 106
loginTag.astBind = 107
loginTag.astQuickStart = 108
url = {}
url.register = "ftgc-gcmob.aoshitang.com/iosRegister.xhtml?pid=%s&pwd=%s"
url.login = "ftgc-gcmob.aoshitang.com/iosLogin.xhtml?pid=%s&pwd=%s"
reigsterKey = "!~app:*:register:*:key~@"
loginKey = "!~app:*:login:*:key~@"
bindKey = "!~app:*:bind:*:key~@"
url.autoRegister = "http://ftgc-gcmob.aoshitang.com/autoRegister.xhtml?ts=%s&ticket=%s"
url.autoLogin = "http://ftgc-gcmob.aoshitang.com/autoLogin.xhtml?ts=%s&tempPlayerID=%s&ticket=%s"
url.autoBind = "http://ftgc-gcmob.aoshitang.com/autoBind.xhtml?ts=%s&tempPlayerID=%s&player_id=%s&password=%s&ticket=%s"
