equipmentKaiguangConstant = {}
equipmentKaiguangConstant.realSuit = {}
equipmentKaiguangConstant.realSuit[1] = "zbxtz.jpg"
equipmentKaiguangConstant.realSuit[2] = "zqhtz.jpg"
equipmentKaiguangConstant.realSuit[3] = "zzltz.jpg"
equipmentKaiguangConstant.realSuit[4] = "zfhtz.jpg"
equipmentKaiguangConstant.realSuit[5] = "zlgtz.jpg"
equipmentKaiguangConstant.jiSuit = {}
equipmentKaiguangConstant.jiSuit[1] = "jbx.jpg"
equipmentKaiguangConstant.jiSuit[2] = "jqh.jpg"
equipmentKaiguangConstant.jiSuit[3] = "jzl.jpg"
equipmentKaiguangConstant.jiSuit[4] = "jfh.jpg"
equipmentKaiguangConstant.jiSuit[5] = "jlg.jpg"

local var_0_0 = 145

equipmentKaiguangConstant.suitPos = {}
equipmentKaiguangConstant.suitPos[0] = {}
equipmentKaiguangConstant.suitPos[0].x = 227
equipmentKaiguangConstant.suitPos[0].y = 308
equipmentKaiguangConstant.suitPos[1] = {}
equipmentKaiguangConstant.suitPos[1].x = 227 + math.sin(math.rad(0)) * var_0_0
equipmentKaiguangConstant.suitPos[1].y = 308 + math.cos(math.rad(0)) * var_0_0
equipmentKaiguangConstant.suitPos[2] = {}
equipmentKaiguangConstant.suitPos[2].x = 227 + math.sin(math.rad(72)) * var_0_0
equipmentKaiguangConstant.suitPos[2].y = 308 + math.cos(math.rad(72)) * var_0_0
equipmentKaiguangConstant.suitPos[3] = {}
equipmentKaiguangConstant.suitPos[3].x = 227 + math.sin(math.rad(144)) * var_0_0
equipmentKaiguangConstant.suitPos[3].y = 308 + math.cos(math.rad(144)) * var_0_0
equipmentKaiguangConstant.suitPos[4] = {}
equipmentKaiguangConstant.suitPos[4].x = 227 + math.sin(math.rad(216)) * var_0_0
equipmentKaiguangConstant.suitPos[4].y = 308 + math.cos(math.rad(216)) * var_0_0
equipmentKaiguangConstant.suitPos[5] = {}
equipmentKaiguangConstant.suitPos[5].x = 227 + math.sin(math.rad(288)) * var_0_0
equipmentKaiguangConstant.suitPos[5].y = 308 + math.cos(math.rad(288)) * var_0_0
equipmentKaiguangConstant.jiSuitName = {}
equipmentKaiguangConstant.jiSuitName[1] = "jbx"
equipmentKaiguangConstant.jiSuitName[2] = "jqh"
equipmentKaiguangConstant.jiSuitName[3] = "jzl"
equipmentKaiguangConstant.jiSuitName[4] = "jfh"
equipmentKaiguangConstant.jiSuitName[5] = "jlg"
equipmentKaiguangConstant.realSuitName = {}
equipmentKaiguangConstant.realSuitName[1] = "zbx"
equipmentKaiguangConstant.realSuitName[2] = "zqh"
equipmentKaiguangConstant.realSuitName[3] = "zzl"
equipmentKaiguangConstant.realSuitName[4] = "zfh"
equipmentKaiguangConstant.realSuitName[5] = "zlg"
