function reload(arg_1_0)
	log.info("@@ reload module ", arg_1_0)

	package.loaded[arg_1_0] = nil

	require(arg_1_0)
end

reload("lua/common/log")
reload("lua/common/helper")
reload("lua/common/platform")
reload("lua/common/tool")
reload("lua/common/utf8")
reload("lua/common/functions")
reload("lua/data/actions")
reload("lua/data/color")
reload("lua/data/country")
reload("res/style")
reload("res/lang_zh_cn")
reload("lua/data/channels")
reload("lua/manager/channelManager")
reload("lua/common/cocosConstants")
reload("lua/common/extern")
reload("lua/common/timer")
reload("lua/common/AudioEngine")
reload("lua/common/http")
reload("lua/ui/autoUI")
reload("lua/common/eventManager")
reload("lua/component/messageBox")
reload("lua/layer/layerConst")
reload("lua/layer/eventConst")
reload("lua/layer/menu/ui")
reload("lua/manager/errorManager")
reload("lua/manager/permissionManager")
reload("lua/component/timerLabel")
reload("lua/component/richNode")
